---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-ai
spec:
  interval: 30m
  chart:
    spec:
      chart: kubernetes/apps/ai/local-ai/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    deployment:
      image:
        repository: localai/localai
        tag: latest-gpu-hipblas

    resources:
      limits:
        amd.com/gpu: 1

    persistence:
      models:
        enabled: true
        existingClaim: local-ai-models
        globalMount: /models
      output:
        enabled: true
        existingClaim: local-ai-output
        globalMount: /tmp/generated
