---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: local-ai
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: infra
      sectionName: websecure
  hostnames: ["local-ai.home.mattprovost.dev"]
  rules:
    - backendRefs:
        - kind: Service
          name: local-ai
