apiVersion: v1
kind: Secret
metadata:
    name: vault-terraform-vars
    namespace: vault-system
type: Opaque
stringData:
    vault_token: ENC[AES256_GCM,data:Ij+2qC81Bb0/lSwbQSFV6ZW/dPgIDhBoQ5+jxg==,iv:/+Eb9UA8npbtMDieu9ftEEDwTUD9cHD0mGoHQ0d3Tqc=,tag:c9OTWowdu7g3FflyLwMWcw==,type:str]
sops:
    age:
        - recipient: age16zd09xxnse2a5hqamq0u93gzr3q3jnqa6qldjrkp8h6hmgrntcuszdrf9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjN09HVmZUZ2NsUEhSSVNE
            eGxvNmtLWCtrb1Q3MTRzajA4aWhoeWpZdjBFCnc4ckpnOVlHUThzQk1KMnRkcEYr
            NVV3N2ZIaU5CYm43cVlhbWluOGJnNWsKLS0tIFlSMUxwcW5qaW9abE56eXZqbmcw
            cXJDTXU2Y1pWVkwrL2RQbldLVlpnd1EKLX7ztZA6YAl83NcCy9Lv4RVKCDd4A/ln
            fc983GRxojvCP7t2RTHu3rBK0VUlO9IVZv4JBJBRdUdZa0+R+FOvyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T21:48:27Z"
    mac: ENC[AES256_GCM,data:HxrSBpoL92sEkV1AEBYtudtW+H+ohz5qB/pR4X+icpWAVgLCUayqjnxAinELbGaRbcOKfyWd9n0IaqEwaDEH4gFeqCH5Ma8SIVuatMv9qb0dXK+FXU8SvwDHXLApaEkqoePzAIEPK+8TaXgAC7E1HaT16a29L+lKhuKDjCXTB78=,iv:ZtfVDWyjuqqz0YUufeid8y0Z8xcEpu9eYG11FoAYIQQ=,tag:883ZACnqLNRRmzWUN2kSJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
