{{- range $key, $pvc := .Values.persistence -}}
  {{- if and ($pvc.enabled) (empty $pvc.existingClaim) -}}
    {{- $pvcObject := dict "name" (printf "%s-%s" (include "local-ai.fullname" $) $key) "accessModes" $pvc.accessModes "size" $pvc.size "storageClass" $pvc.storageClass "annotations" $pvc.annotations "labels" $pvc.labels -}}

    {{- /* Include the PVC template */ -}}
    {{- include "local-ai.pvc" (dict "rootContext" $ "object" $pvcObject) | nindent 0 -}}
  {{- end -}}
{{- end -}}

