---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-gateway
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.808
  url: oci://ghcr.io/berriai/litellm-helm
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm-gateway
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: litellm-gateway
  values:
    image:
      repository: ghcr.io/berriai/litellm
      tag: v1.79.0-stable

    masterkeySecretName: litellm-secret
    masterkeySecretKey: data

    proxy_config:
      model_list:
        - model_name: qwen-2b
          litellm_params:
            model: openai/qwen3-vl-2b-instruct
            api_base: http://local-ai.ai.svc.cluster.local
            api_key: unused
        - model_name: qwen-30b
          litellm_params:
            model: openai/qwen3-vl-30b-instruct
            api_base: http://local-ai.ai.svc.cluster.local
            api_key: unused
        - model_name: gpt-oss
          litellm_params:
            model: openai/gpt-oss-20b
            api_base: http://local-ai.ai.svc.cluster.local
            api_key: unused

    db:
      useExisting: true
      deployStandalone: false

      endpoint: postgres-primary.database.svc.cluster.local
      secret:
        name: litellm-postgres-creds
        usernameKey: username
        passwordKey: password
