---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: litellm
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: infra
      sectionName: websecure
  hostnames: ["ai.home.mattprovost.dev"]
  rules:
    - backendRefs:
        - kind: Service
          name: litellm-gateway
          port: 4000
