---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.media
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

    custom_formats:
      - trash_ids:
          - 9965a052eb87b0d10313b1cea89eb451 # Remux Tier 01
          - 8a1d0c3d7497e741736761a1da866a2e # Remux Tier 02
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
        assign_scores_to:
          - name: WEB-1080p
      - trash_ids:
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
          - d7c747094a7c65f4c2de083c24899e8b # FreeLeech
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster
        assign_scores_to:
          - name: WEB-1080p
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
        assign_scores_to:
          - name: WEB-1080p
      - trash_ids:
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-1080p
            score: -10

    media_naming:
      series: jellyfin-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

radarr:
  radarr:
    base_url: http://radarr.media
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    custom_formats:
      - trash_ids:
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
          - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
        assign_scores_to:
          - name: HD Bluray + WEB
      - trash_ids:
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          - 0d91270a7255a1e388fa85e959f359d8 # FreeLeech
        assign_scores_to:
          - name: HD Bluray + WEB
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - f537cf427b64c38c8e36298f657e4828 # Scene
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
        assign_scores_to:
          - name: HD Bluray + WEB
      - trash_ids:
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: HD Bluray + WEB
            score: -10

    media_naming:
      folder: jellyfin-tmdb
      movie:
        rename: true
        standard: jellyfin-tmdb
