---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname pyroscope
  namespace: &namespace observability
spec:
  targetNamespace: *namespace
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/observability/pyroscope/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
