---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mimir-alertmanager
  namespace: observability
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: infra
      sectionName: websecure
  hostnames:
    - alertmanager.home.mattprovost.dev
  rules:
    - backendRefs:
        - name: mimir-alertmanager
          port: 8080
