---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mimir-alertmanager
  namespace: observability
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: infra
      sectionName: websecure
  hostnames:
    - alertmanager.home.mattprovost.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /alertmanager
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Scope-OrgID
                value: anonymous
      backendRefs:
        - name: mimir-gateway
          port: 80
