---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./obc-mimir.yaml
  - ./helmrelease.yaml
  - ./proxy-config.yaml
  - ./prometheusrules.yaml
  - ./httproute-alertmanager.yaml
