---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-monitoring
spec:
  interval: 30m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.6.1
  url: oci://ghcr.io/grafana/helm-charts/k8s-monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: k8s-monitoring
  dependsOn:
    - name: mimir
      namespace: observability
    - name: loki
      namespace: observability
    - name: tempo
      namespace: observability
  values:
    cluster:
      name: main

    global:
      scrapeClassicHistograms: true
      scrapeNativeHistograms: true
      scrapeProtocols:
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
        - PrometheusText0.0.4
        - PrometheusProto

    destinations:
      - name: mimir
        type: prometheus
        url: http://mimir-gateway.observability.svc.cluster.local/api/v1/push
        extraHeaders:
          X-Scope-OrgID: anonymous
      - name: loki
        type: loki
        url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
      - name: tempo
        type: otlp
        url: http://tempo.observability.svc.cluster.local:4317
        protocol: grpc
        metrics: {enabled: false}
        logs: {enabled: false}
        traces: {enabled: true}

    clusterMetrics:
      enabled: true
      controlPlane:
        enabled: true
      apiServer:
        jobLabel: apiserver
      kubelet:
        jobLabel: kubelet
        nodeAddressFormat: proxy
        extraDiscoveryRules: |
          rule {
            target_label = "metrics_path"
            replacement = "/metrics"
          }
      kubeletResource:
        jobLabel: resources
        nodeAddressFormat: proxy
      cadvisor:
        jobLabel: cadvisor
        nodeAddressFormat: proxy
      kubeDNS:
        jobLabel: kube-dns
      node-exporter:
        jobLabel: node-exporter
        metricsTuning:
          includeMetrics:
            - node_uname_info
      kube-state-metrics:
        jobLabel: kube-state-metrics

    clusterEvents:
      enabled: true

    nodeLogs:
      enabled: true

    podLogs:
      enabled: true

    applicationObservability:
      enabled: true
      receivers:
        grpc:
          enabled: true
          port: 4317
        http:
          enabled: true
          port: 4318
        zipkin:
          enabled: true
          port: 9411
        jaeger:
          grpc:
            enabled: true
            port: 14250
          thriftHttp:
            enabled: true
            port: 14268
          thriftCompact:
            enabled: true
            port: 6831
          thriftBinary:
            enabled: true
            port: 6832
      processors:
        batch:
          maxSize: 100
          timeout: 10s
        resourceDetection:
          enabled: true

    alloy-metrics:
      enabled: true
      extraConfig: |
        mimir.rules.kubernetes "cluster" {
          address               = "http://mimir-gateway.observability.svc.cluster.local"
          tenant_id             = "anonymous"
          prometheus_http_prefix = "/prometheus"
        }

    alloy-logs:
      enabled: true

    alloy-singleton:
      enabled: true

    prometheusOperatorObjects:
      enabled: true
      crds:
        deploy: true

    integrations:
      grafana:
        instances:
          - name: grafana
            labelSelectors:
              app.kubernetes.io/name: grafana
      loki:
        instances:
          - name: loki
            labelSelectors:
              app.kubernetes.io/name: loki
            logs:
              enabled: true
      mimir:
        instances:
          - name: mimir
            labelSelectors:
              app.kubernetes.io/name: mimir
            logs:
              enabled: true
      tempo:
        instances:
          - name: tempo
            labelSelectors:
              app.kubernetes.io/name: tempo
            metrics:
              enabled: true
              portName: prom-metrics
            logs:
              enabled: true

    selfReporting:
      enabled: false
