apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-gotify-token
    namespace: observability
type: Opaque
stringData:
    GOTIFY_TOKEN: ENC[AES256_GCM,data:GN+7qr4uRtcvKJE7KQSR,iv:mWUnXqR057IlQkXFuF334u//n0gPdZefEbinhT08WDs=,tag:c2p1tF/w9Sd9zdZb0qcczA==,type:str]
sops:
    age:
        - recipient: age16zd09xxnse2a5hqamq0u93gzr3q3jnqa6qldjrkp8h6hmgrntcuszdrf9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZnphalFubVpvRnlmd1NW
            dmF1UGVZYW1PMkpaQzJPK1JwR1hSdXlIUlNnCldsZnozUUx5V1pybjZJYU1Pd0la
            YVNiMUdEYTJ1M2Z1cTNOYmdOeG8xWEkKLS0tIGtnNEs3ZitUNXlGMEl5ejlabDRv
            M29YMFJFMGhpVXhSazY0UFY3VTNqYk0KIK3f6dQI2pXJKwxFoXZGiU/N16GXmy5p
            xB0j1CosmzUfqwzobVtn2Wrc9QH3TX91l4WJf/1maTd2GYhcs/T+oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T01:07:20Z"
    mac: ENC[AES256_GCM,data:fa+wpDba03HJxBbwP77f5hovi9nMICczZITtvUTmKlKWAMxXbSGu2P8Iq5aWaRETEne5mrQz1FRlNmF8ZbrLVGZUpTQlTROrd1YqEP9ymf9Hy3qDp11SQ9WblXgCq3tM0NKKiZ1Rnw4GlDCDR6q8q84BizW+7M2VaPJRkN8shIo=,iv:ERCBnULeC1gKd/t/UvBYz00iJqDVTd2HYSRB/uaXY8o=,tag:FFkp9i2iktpKyS0twJDiUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
