---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./metrics-server/ks.yaml
  - ./loki/ks.yaml
  - ./mimir/ks.yaml
  - ./grafana/ks.yaml
  - ./k8s-monitoring/ks.yaml
  - ./karma/ks.yaml
  - ./alertmanager-gotify-bridge/ks.yaml
