---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: amd-gpu-helm
spec:
  interval: 30m
  provider: generic
  timeout: 3m
  url: https://rocm.github.io/k8s-device-plugin/
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocm
spec:
  interval: 30m
  chart:
    spec:
      chart: amd-gpu
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-helm
  values:
    labeller:
      enabled: true
