---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: letta-secret
spec:
  length: 64
  noUpper: false
  allowRepeat: true
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: letta-secret
spec:
  refreshPolicy: CreatedOnce
  target:
    name: letta-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        data: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: letta-secret
