---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./postgres-creds.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./servicemonitor.yaml

configMapGenerator:
  - name: bitmagnet-classifier
    files:
      - classifier.yml=classifier/classifier.yml
generatorOptions:
  disableNameSuffixHash: true
