---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bitmagnet
  namespace: media
  labels:
    app.kubernetes.io/name: bitmagnet
spec:
  namespaceSelector:
    matchNames: ["media"]
  selector:
    matchLabels:
      app.kubernetes.io/name: bitmagnet
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
